DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER
(
    CUSTOMERID INT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(250) NOT NULL,
    EMAIL      VARCHAR(250) DEFAULT NULL,
    STATUS     BOOLEAN      DEFAULT TRUE
);

CREATE TABLE ORDERDATA
(
    ORDERID    INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMERID INT,
    TOTALCOST  DECIMAL(20, 2),
    STATUS     ENUM ('CREATED','INPROGRESS','SHIPPED','COMPLETED','REVIEW')

);